# Generated by Django 4.2.7 on 2023-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Отметьте, если ваше сообщения было прочитано', verbose_name='Прочитано'),
        ),
    ]
